# Jekyll
regenerate: true

# Sitio
title: Video-Toys
description: 'Sitio de juegos'
tagline: "Encuentra las mejores ofertas en juegos"
url: jfrn.github.io/videotoysDI
baseurl: http://jfrn.github.io/videotoysDI
timezone: America/Mexico_City
encoding: utf-8
permalink: pretty
# Directivas
markdown: kramdown
kramdown:
 # Usar GitHub Flavored Markdown
 input: GFM
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  css_class: 'highlight'

gems:
  - jekyll-sitemap # Para crear un mapa del sitio
  - jekyll-gist
  - sass
sass:
  sass_dir: _sass
  style: expanded

exclude:
 - Gemfile
 - Gemfile.lock
 - LICENSE
 - README.md
 - CNAME
 - _trash
